### ISSUE TITLE
Sessions with null activity types

### ISSUE THREAD

**Issue by tomoakley** [GLL-Better/opendata#1]
Some sessions have `"activity": null` - specifically the Sauna sessions. I've looked in the activities feed and can't find a Sauna activity so I'd guess it's looking up the activity name, not finding Sauna (and maybe others) so assigning it null?

Thanks!

**Comment by itsterry** [comment]
Yes, that sounds about right. We have some 'legacy' data hanging around which it looks like we need to deal with. I'll exclude records with null activities from the feed

**Comment by itsterry** [comment]
That's live now
