### ISSUE TITLE
Error in feed

### ISSUE THREAD

**Issue by house92** [GLL-Better/opendata#14]
I noticed that your feed is broken on a particular page: https://www.better.org.uk/odi/sessions.json?afterTimestamp=2018-03-22T18:17:09&afterId=20573905. This prevents your feed from being read any further than this point, so is this something that could be quickly/easily resolved?

**Comment by itsterry** [comment]
Fixed. Please try it now



----------------------------------------------
Terry Shuttleworth
Morse Digital LLP

terry@morsedigital.com

Voice
-----
Mobile: +44 (0) 77 68 91 81 93
Office: +44 (0) 20 7193 0909

IM
--
Google Chat: itsterry@gmail.com
Skype: itsterry

Company
-------
Registered in England No. OC368394
Vat No. GB 122 2042 79
