### ISSUE TITLE
Time is incorrect for all sessions! (likely timezone funsies)

### ISSUE THREAD

**Issue by lukehesluke** [GLL-Better/opendata#18]
Hi,

Big fan of the feed

However, we (at [imin](https://imin.co)) have noticed a rather severe issue with the data - all session datetimes are out by 2 hours!

An example:

Example:

- Session found in the feed (https://www.better.org.uk/odi/sessions.json) with ID `19876313`
  ```
  {
    "state": "updated",
    "kind": "session",
    "id": 19876313,
    "modified": "2017-11-11T12:53:41",
    "data": {
      "type": "Event",
      "url": "https://better.org.uk/leisure-centre/west-oxfordshire/bartholomew-sports-centre/timetable",
      "name": "Functional",
      "genderRestriction": "mixed",
      "location": {
        "type": "SportsActivityLocation",
        "name": "Main Hall",
        "containedInPlace": {
          "type": "Place",
          "url": "https://better.org.uk/leisure-centre/west-oxfordshire/bartholomew-sports-centre",
          "name": "Bartholomew Sports Centre, Eynsham",
          "address": {
            "type": "PostalAddress",
            "addressLocality": "West Ox",
            "addressRegion": "West",
            "postalCode": "OX29 4AP",
            "streetAddress": "Bartholomew Sports Centre"
          },
          "geo": {
            "latitude": 51.7827,
            "longitude": -1.38108
          },
          "telephone": "01865 731090"
        }
      },
      "organizer": {
        "type": "Organization",
        "name": "Better"
      },
      "activity": {
        "type": "Concept",
        "notation": 16,
        "prefLabel": "Fitness Classes",
        "inScheme": "https://better.org.uk/odi/activities"
      },
      "eventStatus": "EventScheduled",
      "level": "All",
      "ageRange": "16-55",
      "contributor": {
        "type": "Person",
        "name": "Kat"
      },
      "description": "<p>Get better strength and balance. The exercises in this session are designed to help you train and prepare your body for daily tasks by simulating common movements and muscles you use everyday at home, work or during sports.</p>\r\n<p>Better for: Overall strength, coordination and balance.</p>\r\n<p><iframe src=\"//www.youtube.com/embed/wA9woUsf75A\" width=\"560\" height=\"315\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe></p>",
      "image": "https://assets.better.org.uk/uploads/asset/attachment/41037/418963_GLL_AdHoc_Image_resize_750x330_Mar18.jpg",
      "offer": {
        "url": "https://better.legendonlineservices.co.uk/enterprise/account/Login",
        "type": "Offer"
      },
      "startDate": "2018-08-05T10:30:00Z",
      "endDate": "2018-08-05T11:00:00Z",
      "duration": "PT30M",
      "@context": "https://www.openactive.io/ns/oa.jsonld"
    }
  }
  ```
  - Date: Sunday 5th August
  - Time: 10:30 (UTC)
  - Name: "Functional"
- Timetable for sessions in this leisure centre: https://www.better.org.uk/leisure-centre/west-oxfordshire/bartholomew-sports-centre/timetable
  - Only class with name "Functional" on Sunday 5th has time: 09:30 (assumed BST) i.e. 08:30 UTC, **2 hours earlier than time on the feed**

I imagine the issue here is something like the conversion from BST to UTC accidentally going the wrong way round. So rather than converting a 09:30 from BST (+01:00)  to UTC (+00:00) by subtracting an hour (08:30) it has accidentally moved it to +02:00 (Egyptian time) by adding an hour. A `Z` has then been appended to the end of the time in order to label it (incorrectly) as UTC

Until this is fixed, we are going to have to manually subtract 2 hours from every time until we hear otherwise

So please let us know if and when you get to work on this so that we can remove our fix ASAP and ensure customers don't end up going to Leisure Centres 2 hours late!

**Comment by GetTheData** [comment]
I am also seeing this issue - the difference drops to 1 hour once the clocks change.

**Comment by itsterry** [comment]
I think this is fixed now. Could someone verify for me please?

**Comment by GetTheData** [comment]
Confirming this is now fixed - thanks @itsterry !
