### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by civsiv** [GLL-Better/opendata#19]
Hi,

Civ from imin here. This link, https://www.better.org.uk/odi/sessions.json?afterTimestamp=2018-10-29T08:53:18&afterId=28276938, causes an internal server error :(  Are you aware of this?

Thanks,
Civ

**Comment by itsterry** [comment]
Hi Civ

Hadn't spotted that: looks like some old data. Should be working for you now

T
