### ISSUE TITLE
URLs have the domain "http://gll2.morsestaging.com" instead of a customer facing site

### ISSUE THREAD

**Issue by tomoakley** [GLL-Better/opendata#2]
The URLs on your sessions (`data.url` and `data.location.containedInPlace.url`) uses http://gll2.morsestaging.com - for example, `"url": "http://gll2.morsestaging.com/leisure-centre/hackney/britannia-leisure-centre/timetable"`, whereas I'd imagine it should be something like http://www.better.org.uk/.

**Comment by itsterry** [comment]
I suspect you're looking at the staging server feed, which is just for our
internal data.

The live data is at https://www.better.org.uk/odi/sessions.json

T



----------------------------------------------
Terry Shuttleworth
Morse Digital LLP

terry@morsedigital.com

Voice
-----
Mobile: +44 (0) 77 68 91 81 93
Office: +44 (0) 20 7193 0909

IM
--
Google Chat: itsterry@gmail.com
Skype: itsterry

Company
-------
Registered in England No. OC368394
Vat No. GB 122 2042 79

**Comment by tomoakley** [comment]
ah sure, thanks!
