### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by GetTheData** [GLL-Better/opendata#23]
Hi @itsterry 

If I try and do a full fetch, i.e. page through the entire feed, I get a HTTP 500 at the same place each time:

https://better.org.uk/odi/sessions.json?afterTimestamp=2018-12-05T11:25:03&afterId=20232629

This is linked to from here, which works:

https://better.org.uk/odi/sessions.json?afterTimestamp=2018-12-05T11:00:26&afterId=34384703

I've been seeing this since yesterday afternoon.

**Comment by itsterry** [comment]
Thanks @GetTheData  - that's giving me an error I haven't seen before. I'll investigate and report back

**Comment by itsterry** [comment]
Hi @GetTheData 

That should be fixed for you now

**Comment by GetTheData** [comment]
Thanks @itsterry looks good from my end!

Interestingly I now seem to have the Sobell items too.

Thanks for your help - I'll close this off.
