### ISSUE TITLE
Biggin Hill Memorial Library: Typo in location name

### ISSUE THREAD

**Issue by GetTheData** [GLL-Better/opendata#24]
This location appears to have a typo in the **name** field:

BigginHill Memorial Library and Pool

I would expect it to be:

Biggin Hill Memorial Library and Pool

The **containedInPlace/name** field is correct:

Biggin Hill Memorial Library

**Comment by itsterry** [comment]
Fixed

**Comment by GetTheData** [comment]
Thanks @itsterry - confirm fixed.
