### ISSUE TITLE
Gunnersbury Park Sports Hub: location/name=test

### ISSUE THREAD

**Issue by GetTheData** [GLL-Better/opendata#25]
The **name** field for all Gunnersbury Park Sports Hub locations appears to be "test".

You can see this in an extract of all upcoming items for Gunnersbury Park Sports Hub here:

https://www.getthedata.com/openactive/gunnersbury-park-sports-hub-w3-8lq

Screenshot:

![image](https://user-images.githubusercontent.com/35957529/55728920-0a932180-5a0d-11e9-97ac-f674013103a6.png)

**Comment by itsterry** [comment]
Hi @GetTheData 

Not sure how you're getting this, to be honest

The 'Place' data calls (in our system) `venue.title` for the 'name' attribute, and the title for that venue is set to 'Gunnersbury Park Sports Hub'

Can you give me an ID number for one of those instances so I can check the stream and see if we're outputting it with 'test' anywhere?

**Comment by itsterry** [comment]
Scratch that: I found the issue. Gunnersbury sports hub has a location called 'test'. It's the only location, so I've changed its name to 'Gunnersbury Sports Hub'

**Comment by GetTheData** [comment]
Hi @itsterry I've pulled an update and confirm the issue has been resolved. See below. Thank you for your prompt attention!

![image](https://user-images.githubusercontent.com/35957529/55789959-497bb280-5ab3-11e9-8222-43c91cb64096.png)
