### ISSUE TITLE
Clarity around number of sessions in the RPDE feed

### ISSUE THREAD

**Issue by domfennell** [GLL-Better/opendata#26]
Hi @itsterry,

Hope you're well and having a good week.

We have noticed a decrease in the amount of sessions coming from your endpoint. Has something changed or do you think this is an issue our side? We were wondering if it might have something to do with the duplication issue you mention in [issue 20](https://github.com/GLL-Better/opendata/issues/20#issuecomment-477394544)?

It would be very much appreciated if you could provide us with:

- the total number of items we should expect to see in the feed; and
- (if possible) the number of sessions taking place over a forthcoming 7-day period.

Any help gratefully received,

Dom

cc @GetTheData

**Comment by domfennell** [comment]
Hi @itsterry @GLL-Digital,

Hope you enjoyed the long weekend.

Any thoughts on this would be greatly appreciated. We're keen to understand if/why there might have been a decrease in sessions numbers in the endpoint, so we can establish whether we have the correct number in our platform.

Best,

Dom

**Comment by itsterry** [comment]
Hi @domfennell 

Just checking: is this still an issue?

T

**Comment by domfennell** [comment]
Hi @itsterry,

It's hard to say without knowing how many future sessions are in your feed. Is this a number you would be able to provide?

Thanks,

Dom

**Comment by itsterry** [comment]
It changes constantly. Would you like me to whip up a quick API endpoint that gives you the number on demand?

**Comment by domfennell** [comment]
Completely understand, Terry. That would be very helpful, if it's not too much trouble. Alternatively, just a ballpark figure would be great.

**Comment by itsterry** [comment]
https://www.better.org.uk/odi/sessions/count

**Comment by domfennell** [comment]
Many thanks, Terry.
