### ISSUE TITLE
SSL cert issue

### ISSUE THREAD

**Issue by GetTheData** [GLL-Better/opendata#27]
Hi @GLL-Digital 

It looks like your SSL cert is missing the intermediate/chain certificate:

https://www.sslshopper.com/ssl-checker.html#hostname=https://www.better.org.uk

Thanks
Dan

**Comment by itsterry** [comment]
Hi Dan

Is this causing an issue?

T

**Comment by GetTheData** [comment]
Hi @itsterry it causes me an issue because CURL throws an error when trying to connect to the feed. My understanding is that CURL is stricter than many browsers, however you might find that stricter browsers are also refusing to connect to your public site.

You can see here that Qualys SSL Labs report the same error:

https://www.ssllabs.com/ssltest/analyze.html?d=www.better.org.uk

_This server's certificate chain is incomplete. Grade capped to B._

I do however have a work around so if you're not concerned than I don't want to make unnecessary work for you!

**Comment by itsterry** [comment]
Hi @GetTheData 

I'll get our ISP on to it now

**Comment by itsterry** [comment]
That's fixed now and showing A+ grade

**Comment by GetTheData** [comment]
Thanks @itsterry all working for me now!
