### ISSUE TITLE
Morden Park Pools and Morden Leisure Centre

### ISSUE THREAD

**Issue by GetTheData** [GLL-Better/opendata#28]
Hi @GLL-Digital 

I'm seeing items for two separate locations, Morden Park Pools and Morden Leisure Centre, both of which have the same address.

Is this correct?

It looks like perhaps two locations have merged based on the main GLL website.

Thanks
Dan

**Comment by itsterry** [comment]
Hi @GetTheData 

Good spot: Morden Park Pools has been archived on our system, but still had some surviving sessions.

I've marked them as deleted, which means they'll show as deleted in your feed until the time comes to expire them fully

T

**Comment by GetTheData** [comment]
Thanks Terry, I'll check again tomorrow - when I have a new full fetch - and confirm.

Cheers
Dan

**Comment by GetTheData** [comment]
Hi @itsterry 

All sorted - thanks for your help on this one!

Cheers
Dan
