### ISSUE TITLE
Dormers Wells Leisure Centre/Wythenshawe Forum

### ISSUE THREAD

**Issue by GetTheData** [GLL-Better/opendata#29]
Hi @GLL-Digital 

It looks like both **Dormers Wells Leisure Centre** and **Wythenshawe Forum** still have items, but have moved over to Everyone Active:

https://www.everyoneactive.com/centre/dormers-wells-leisure-centre/

https://www.everyoneactive.com/centre/wythenshawe-forum/

Thanks
Dan

**Comment by itsterry** [comment]
They're marked as 'draft' on our system rather than 'archived', so I can't
delete them without checking

Have asked the question...

T

**Comment by itsterry** [comment]
Have had the okay to delete those sessions, so they are **gone**

**Comment by GetTheData** [comment]
Thanks @itsterry !
