### ISSUE TITLE
Page size increase

### ISSUE THREAD

**Issue by nickevansuk** [GLL-Better/opendata#3]
Can we increase the page size from 50 to 500? This will greatly increase accessibility of the data.

**Comment by itsterry** [comment]
That's done. It'll go live with the next code deploy



----------------------------------------------
Terry Shuttleworth
Morse Digital LLP

terry@morsedigital.com

Voice
-----
Mobile: +44 (0) 77 68 91 81 93
Office: +44 (0) 20 7193 0909

IM
--
Google Chat: itsterry@gmail.com
Skype: itsterry

Company
-------
Registered in England No. OC368394
Vat No. GB 122 2042 79

**Comment by nickevansuk** [comment]
Awesome, thanks Terry!

**Comment by itsterry** [comment]
This is live now: https://www.better.org.uk/odi/sessions.json
