### ISSUE TITLE
Updates to activity list

### ISSUE THREAD

**Issue by nickevansuk** [GLL-Better/opendata#4]
Reviewing the activity list, there's a few changes required to bring it in line with the modelling spec and primer:
- `inScheme` should be `concepts` for the array of concepts.
- It should include `"@context": "https://www.openactive.io/ns/oa.jsonld"`.
- It should include `"license": "https://creativecommons.org/licenses/by/4.0/"`
- It should include `"notation": "123"` for the internal ID of that activity in your database
- It should include `"title"` instead of `"description"` if only one of these is specified

See this link for a conformant example: 
http://www.client1.sport.sportstarta.com/api/concepts/activities

Example of resulting output after above changes made as follows:
```
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "ConceptScheme",
  "url": "https://better.org.uk/odi/activities",
  "title": "Activities at Better Leisure Centres",
  "concepts": [
    {
      "type": "Concept",
      "prefLabel": "Active for Life",
      "notation": "123",
    },
    ...
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
```

**Comment by itsterry** [comment]
Confirming:

inScheme changed to concepts

@context is already there (check end of list at
https://www.better.org.uk/odi/activities.json )

license is already there (check end of list at
https://www.better.org.uk/odi/activities.json )

notation has been added


These changes will go live with next code deployment (should be today at
some point)




----------------------------------------------
Terry Shuttleworth
Morse Digital LLP

terry@morsedigital.com

Voice
-----
Mobile: +44 (0) 77 68 91 81 93
Office: +44 (0) 20 7193 0909

IM
--
Google Chat: itsterry@gmail.com
Skype: itsterry

Company
-------
Registered in England No. OC368394
Vat No. GB 122 2042 79

**Comment by itsterry** [comment]
I think we can close this one now?

Live url: https://www.better.org.uk/odi/activities.json

**Comment by nickevansuk** [comment]
Just missing one point from above:
- It should include "title" instead of "description" if only one of these is specified

All else looks great :)

**Comment by itsterry** [comment]
How's this?: https://www.better.org.uk/odi/activities.json

**Comment by nickevansuk** [comment]
bellissimo :)
