### ISSUE TITLE
Leisure Centre URLs sometimes redirect to the main Better site

### ISSUE THREAD

**Issue by tomoakley** [GLL-Better/opendata#5]
Some of the URLs that are provided for leisure centres redirect to the main Better URL. For example:

- https://better.org.uk/leisure-centre/westminster/porchester-centre/timetable
- https://better.org.uk/leisure-centre/westminster/seymour-leisure-centre/timetable
- https://better.org.uk/leisure-centre/westminster/littlevenicesportscentre/timetable

Not sure if this is just Westminster leisure centres, but they're the ones I could find that did redirect.

**Comment by itsterry** [comment]
The centres that redirected were those that were no longer live. We've rewritten the feed to exclude activities for centres that are no longer live
